import fs from "node:fs";
import path from "node:path";
import { ensureWorkspace } from "./workspace.js";
import { config } from "./config.js";

/** Ensure user workspace has project markers for OpenCode / OpenChamber */
export function bootstrapUserWorkspace(username: string): string {
  const root = ensureWorkspace(config.workspacesRoot, username);

  const vibeMeta = {
    username,
    workspace: root,
    platform: "codeharbor",
    updatedAt: new Date().toISOString(),
  };
  fs.writeFileSync(
    path.join(root, ".vibe.json"),
    JSON.stringify(vibeMeta, null, 2),
    "utf8",
  );

  const agentsPath = path.join(root, "AGENTS.md");
  if (!fs.existsSync(agentsPath)) {
    fs.writeFileSync(
      agentsPath,
      `# Workspace: ${username}

This directory is the **isolated workspace** for platform user \`${username}\`.

- Prefer creating and editing files **inside this folder only**.
- Do not access sibling user workspaces.
- Prefer small, incremental changes.

Generated by CodeHarbor.
`,
      "utf8",
    );
  }

  const readmePath = path.join(root, "README.md");
  if (!fs.existsSync(readmePath)) {
    fs.writeFileSync(
      readmePath,
      `# ${username} workspace

Open this folder in OpenChamber / OpenCode as the project root.

Platform path: \`${root}\`
`,
      "utf8",
    );
  }

  return root;
}
